server:
  port: 9090


    #配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erp?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource  #指定使用某个数据源
  servlet:
    multipart:
      max-file-size: 50MB   #单个文件最大size
      max-request-size: 200MB  #总文件最大的size

#配置日志输出级别  以及指定包
logging:
  level:
    com.guigu.mapper: debug
    #org.springframework: debug



#mybatis-plus配置
mybatis-plus:
  type-aliases-package:  com.guigu.pojo   #指定别名 (mapper.xml中可以直接使用类名)


# 添加分页配置信息
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true
